//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressCitizen
    {
        public int Id { get; set; }
        public int CA_CitizenId { get; set; }
        public int CA_AddressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Citizen Citizen { get; set; }
    }
}
