//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreasAuthorityRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreasAuthorityRequest()
        {
            this.RealStateRegistryInterestReports = new HashSet<RealStateRegistryInterestReport>();
        }
    
        public int AreasAuthorityRequest_id { get; set; }
        public string AreasAuthorityRequest_number { get; set; }
        public Nullable<int> AreasAuthorityRequests_District_id { get; set; }
        public string AreasAuthorityRequests_length { get; set; }
        public string AreasAuthorityRequests_width { get; set; }
        public string AreasAuthorityRequests_LWnumber { get; set; }
    
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealStateRegistryInterestReport> RealStateRegistryInterestReports { get; set; }
    }
}
