//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarLicence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarLicence()
        {
            this.Violation_CarLicenceM_M = new HashSet<Violation_CarLicenceM_M>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CitizenId { get; set; }
        public string CarName { get; set; }
        public string CarCode { get; set; }
        public string CarNameArabic { get; set; }
        public Nullable<int> CarModel { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<int> CarId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Citizen Citizen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Violation_CarLicenceM_M> Violation_CarLicenceM_M { get; set; }
    }
}
