//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateStudentM_M
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> CertificateId { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> GraduationProjectGradeId { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Grade Grade1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
