//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Certificate()
        {
            this.GradesCertificateM_M = new HashSet<GradesCertificateM_M>();
            this.SchoolCertificateM_M = new HashSet<SchoolCertificateM_M>();
            this.CertificateStudentM_M = new HashSet<CertificateStudentM_M>();
            this.FacultyCertificateM_M = new HashSet<FacultyCertificateM_M>();
        }
    
        public int Id { get; set; }
        public string CirtificateTypeName { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string CirtificateTypeNameArabic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradesCertificateM_M> GradesCertificateM_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolCertificateM_M> SchoolCertificateM_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificateStudentM_M> CertificateStudentM_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacultyCertificateM_M> FacultyCertificateM_M { get; set; }
    }
}
