//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complains
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complains()
        {
            this.Responds = new HashSet<Responds>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CitizenId { get; set; }
        public string CitizenNationalId { get; set; }
        public Nullable<int> GovernementId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ComplainText { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual governement_body governement_body { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responds> Responds { get; set; }
    }
}
