//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contact_id { get; set; }
        public string contact_data { get; set; }
        public Nullable<int> contact_citizen_id { get; set; }
        public Nullable<int> contact_contactType_id { get; set; }
        public Nullable<bool> contact_isDeleted { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Contact_Type Contact_Type { get; set; }
    }
}
