//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deceased
    {
        public int deceased_id { get; set; }
        public Nullable<int> deceased_citizenId { get; set; }
        public string deceased_deathDate { get; set; }
        public string deceased_deathPlace { get; set; }
        public string deceased_deathCause { get; set; }
        public Nullable<bool> deceased_isDeleted { get; set; }
        public string deceased_deathCause_arabic { get; set; }
        public string deceased_deathPlace_arabic { get; set; }
    
        public virtual Citizen Citizen { get; set; }
    }
}
