//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorScheduleM_M
    {
        public int doctorSchedule_id { get; set; }
        public Nullable<int> doctorSchedule_doctor { get; set; }
        public Nullable<int> doctorSchedule_schedule { get; set; }
    
        public virtual Healthcare_Doctor Healthcare_Doctor { get; set; }
        public virtual ScheduleHealthCare ScheduleHealthCare { get; set; }
    }
}
