//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Detail
    {
        public int document_detail_id { get; set; }
        public int documentDetail_document_id { get; set; }
        public int documentDetail_citizen_id { get; set; }
        public string document_detail_description { get; set; }
        public Nullable<bool> document_detail_isDeleted { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Document Document { get; set; }
    }
}
