//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Document_Detail = new HashSet<Document_Detail>();
        }
    
        public int document_id { get; set; }
        public string document_data { get; set; }
        public int document_citizen_id { get; set; }
        public int document_documentType_id { get; set; }
        public string document_name { get; set; }
        public string document_extensions { get; set; }
        public Nullable<bool> document_isDeleted { get; set; }
        public string document_date_upload { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_Detail> Document_Detail { get; set; }
        public virtual Document_Type Document_Type { get; set; }
    }
}
