//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculty()
        {
            this.Coordinations = new HashSet<Coordination>();
            this.SpecializationOfFaculties = new HashSet<SpecializationOfFaculty>();
            this.Students = new HashSet<Student>();
            this.FacultyCertificateM_M = new HashSet<FacultyCertificateM_M>();
            this.UniversityFacultyM_M = new HashSet<UniversityFacultyM_M>();
        }
    
        public int Id { get; set; }
        public string FacultyName { get; set; }
        public Nullable<bool> Is_Dleted { get; set; }
        public Nullable<int> Year { get; set; }
        public string FacultyNameArabic { get; set; }
        public string SchoolSection { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coordination> Coordinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecializationOfFaculty> SpecializationOfFaculties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacultyCertificateM_M> FacultyCertificateM_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UniversityFacultyM_M> UniversityFacultyM_M { get; set; }
    }
}
