//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthCare()
        {
            this.HealthCareDoctorM_M = new HashSet<HealthCareDoctorM_M>();
            this.HealthcareReservations = new HashSet<HealthcareReservation>();
            this.HealthCareSpecializationM_M = new HashSet<HealthCareSpecializationM_M>();
            this.HealthCareSheduleM_M = new HashSet<HealthCareSheduleM_M>();
            this.ScheduleVaccM_M = new HashSet<ScheduleVaccM_M>();
            this.VaccinationReservations = new HashSet<VaccinationReservation>();
            this.VacinationHealthCareM_M = new HashSet<VacinationHealthCareM_M>();
        }
    
        public int hospital_id { get; set; }
        public string hospital_name { get; set; }
        public Nullable<int> healthcare_type_id { get; set; }
        public Nullable<int> hospital_district_id { get; set; }
        public Nullable<bool> hospital_isDeleted { get; set; }
        public Nullable<System.TimeSpan> healthcare_open { get; set; }
        public Nullable<System.TimeSpan> healthcare_close { get; set; }
        public string hospital_name_arabic { get; set; }
    
        public virtual District District { get; set; }
        public virtual HealthCare_Type HealthCare_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthCareDoctorM_M> HealthCareDoctorM_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthcareReservation> HealthcareReservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthCareSpecializationM_M> HealthCareSpecializationM_M { get; set; }
        public virtual HealthCare HealthCare1 { get; set; }
        public virtual HealthCare HealthCare2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthCareSheduleM_M> HealthCareSheduleM_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleVaccM_M> ScheduleVaccM_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccinationReservation> VaccinationReservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacinationHealthCareM_M> VacinationHealthCareM_M { get; set; }
    }
}
