//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCareSpecializationM_M
    {
        public int hospitalSpecialization_id { get; set; }
        public Nullable<int> hospitalSpecialization_hospital_id { get; set; }
        public Nullable<int> hospitalSpecialization_specialization_id { get; set; }
    
        public virtual HealthCare HealthCare { get; set; }
        public virtual HealthCareSpecialization HealthCareSpecialization { get; set; }
    }
}
