//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthcareReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthcareReservation()
        {
            this.ReservationScheduleM_M = new HashSet<ReservationScheduleM_M>();
        }
    
        public int healthcareReservation_id { get; set; }
        public Nullable<int> healthcareReservation_hospital_id { get; set; }
        public Nullable<System.DateTime> Reservation_date { get; set; }
        public Nullable<bool> healthcareReservation_isDeleted { get; set; }
        public Nullable<int> healthcareReservation_doctor_id { get; set; }
        public Nullable<int> healthcareReservation_citizen_id { get; set; }
        public string healthcareReservation_Code { get; set; }
        public Nullable<bool> healthcareReservation_cancel { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual HealthCare HealthCare { get; set; }
        public virtual Healthcare_Doctor Healthcare_Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationScheduleM_M> ReservationScheduleM_M { get; set; }
    }
}
