//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCareSpecializations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthCareSpecializations()
        {
            this.Healthcare_Doctor = new HashSet<Healthcare_Doctor>();
            this.HealthCareSpecializationM_M = new HashSet<HealthCareSpecializationM_M>();
        }
    
        public int specialization_id { get; set; }
        public string specialization_name { get; set; }
        public Nullable<bool> specialization_isDeleted { get; set; }
        public string specialization_name_arabic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Healthcare_Doctor> Healthcare_Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthCareSpecializationM_M> HealthCareSpecializationM_M { get; set; }
    }
}
