//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCareScheduleM_M
    {
        public int hospitalSchedule_id { get; set; }
        public Nullable<int> hospitalSchedule_hospital { get; set; }
        public Nullable<int> hospitalSchedule_schedule { get; set; }
    
        public virtual HealthCare HealthCare { get; set; }
        public virtual ScheduleHealthCare ScheduleHealthCare { get; set; }
    }
}
