//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCare_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthCare_Type()
        {
            this.HealthCares = new HashSet<HealthCare>();
        }
    
        public int healthcare_type_id { get; set; }
        public string healthcare_type_name { get; set; }
        public Nullable<bool> healthcare_isDeleted { get; set; }
        public string healthcare_type_name_arabic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthCare> HealthCares { get; set; }
    }
}
