//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Live_Status
    {
        public int live_satus_id { get; set; }
        public int live_satus_type_id { get; set; }
        public int citizen_citizen_id { get; set; }
        public Nullable<bool> live_satus_isDeleted { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Live_Status_Type Live_Status_Type { get; set; }
    }
}
