//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginCitizen
    {
        public int LoginId { get; set; }
        public string Login_CitizenNId { get; set; }
        public string Login_Password { get; set; }
        public string Login_PinNumber { get; set; }
        public Nullable<int> Login_CitizenId { get; set; }
        public string Login_QRcode { get; set; }
    
        public virtual Citizen Citizen { get; set; }
    }
}
