//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogRequest
    {
        public int log_request_id { get; set; }
        public Nullable<int> log_requestId { get; set; }
        public Nullable<int> log_citizenId { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public Nullable<int> log_request_typeId { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Request Request { get; set; }
        public virtual TypeRequest TypeRequest { get; set; }
    }
}
