//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Office()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int office_id { get; set; }
        public string office_name { get; set; }
        public Nullable<int> office_district_id { get; set; }
        public Nullable<bool> office_isDeleted { get; set; }
        public Nullable<int> governemet_id { get; set; }
        public string office_name_arabic { get; set; }
    
        public virtual District District { get; set; }
        public virtual governement_body governement_body { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
