//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhasesOfSchoole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhasesOfSchoole()
        {
            this.SchoolPhasesM_M = new HashSet<SchoolPhasesM_M>();
        }
    
        public int Id { get; set; }
        public string PhaseName { get; set; }
        public Nullable<int> Year { get; set; }
        public string PhaseNameArabic { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolPhasesM_M> SchoolPhasesM_M { get; set; }
    }
}
