//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class police_report
    {
        public int police_report_id { get; set; }
        public Nullable<int> police_report_number { get; set; }
        public Nullable<int> police_report_classification_id { get; set; }
        public Nullable<int> police_report_policeDepartment { get; set; }
        public string police_report_body { get; set; }
        public Nullable<int> police_report_police_signature { get; set; }
        public Nullable<int> police_report_accused_signature { get; set; }
        public Nullable<System.DateTime> police_report_DateAndTime { get; set; }
        public Nullable<int> police_report_type { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Citizen Citizen1 { get; set; }
        public virtual PoliceReport_type PoliceReport_type { get; set; }
        public virtual PoliceDepartment PoliceDepartment { get; set; }
        public virtual PoliceReportClassification PoliceReportClassification { get; set; }
    }
}
