//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealStateRegistryInterestReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealStateRegistryInterestReports()
        {
            this.RSRIPersonalRegistry = new HashSet<RSRIPersonalRegistry>();
            this.RSRISpecificRegistry = new HashSet<RSRISpecificRegistry>();
        }
    
        public int realStateRegistryInterest_reports_id { get; set; }
        public Nullable<int> realStateRegistryInterest_reports_subject { get; set; }
        public Nullable<int> realStateRegistryInterest_reports_vendor_id { get; set; }
        public Nullable<int> realStateRegistryInterest_reports_buyer_id { get; set; }
        public Nullable<int> realStateRegistryInterest_reports_Places_id { get; set; }
        public Nullable<int> realStateRegistryInterest_reports_popularContract_id { get; set; }
        public Nullable<int> realStateRegistryInterest_reports_propertyTaxes_id { get; set; }
        public string realStateRegistryInterest_reports_price { get; set; }
        public Nullable<int> realStateRegistryInterest_reports_request { get; set; }
        public string realStateRegistryInterest_reports_number { get; set; }
        public Nullable<System.DateTime> realStateRegistryInterest_reports_Date { get; set; }
        public Nullable<int> realStateRegistryInterestBranch_id { get; set; }
    
        public virtual AreasAuthorityRequests AreasAuthorityRequests { get; set; }
        public virtual Citizen Citizen { get; set; }
        public virtual Citizen Citizen1 { get; set; }
        public virtual District District { get; set; }
        public virtual RealStateRegistryInterestBranch RealStateRegistryInterestBranch { get; set; }
        public virtual RealStateRegistryInterestPopularContract RealStateRegistryInterestPopularContract { get; set; }
        public virtual RealStateRegistryInterestPropertyTaxes RealStateRegistryInterestPropertyTaxes { get; set; }
        public virtual RealStateRegistryInterestReportsSubject RealStateRegistryInterestReportsSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSRIPersonalRegistry> RSRIPersonalRegistry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSRISpecificRegistry> RSRISpecificRegistry { get; set; }
    }
}
