//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Ambulance
    {
        public int Id { get; set; }
        public Nullable<decimal> location_latitude { get; set; }
        public Nullable<decimal> location_longitude { get; set; }
        public string request_details { get; set; }
        public Nullable<int> request_citizenId { get; set; }
        public Nullable<System.DateTime> request_Date { get; set; }
        public Nullable<bool> request_isDeleted { get; set; }
        public Nullable<bool> request_isFinshed { get; set; }
    
        public virtual Citizen Citizen { get; set; }
    }
}
