//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSRISpecificRegistry
    {
        public int RSRI_specific_registry_id { get; set; }
        public Nullable<int> RSRI_specific_registry_reports_id { get; set; }
    
        public virtual RealStateRegistryInterestReport RealStateRegistryInterestReport { get; set; }
    }
}
