//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleVaccReservationM_M
    {
        public int ScheduleVaccReservation_id { get; set; }
        public int ScheduleVaccReservation_schedule_id { get; set; }
        public Nullable<int> ScheduleVaccReservation_reservationVacc_id { get; set; }
    
        public virtual ScheduleVaccination ScheduleVaccination { get; set; }
        public virtual VaccinationReservation VaccinationReservation { get; set; }
    }
}
