//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleVaccM_M
    {
        public int scheduleVacc_id { get; set; }
        public Nullable<int> scheduleVacc_vaccType_id { get; set; }
        public Nullable<int> scheduleVacc_schedule_id { get; set; }
        public Nullable<int> HealthCareId { get; set; }
    
        public virtual HealthCare HealthCare { get; set; }
        public virtual ScheduleVaccination ScheduleVaccination { get; set; }
        public virtual VaccinationType VaccinationType { get; set; }
    }
}
