//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social_Status_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Social_Status_Type()
        {
            this.Social_status = new HashSet<Social_status>();
        }
    
        public int social_status_type_id { get; set; }
        public string social_status_type_name { get; set; }
        public string social_status_type_description { get; set; }
        public Nullable<bool> social_status_type_isDeleted { get; set; }
        public string social_status_type_name_arabic { get; set; }
        public string social_status_type_description_arabic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Social_status> Social_status { get; set; }
    }
}
