//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social_status
    {
        public int social_status_id { get; set; }
        public int socialStatus_citizenId_Husband { get; set; }
        public int socialStatus_citizenId_Wife { get; set; }
        public int socialStatus_TypeId { get; set; }
        public System.DateTime social_status_from { get; set; }
        public Nullable<System.DateTime> social_status_to { get; set; }
        public Nullable<bool> social_status_isStill { get; set; }
        public Nullable<bool> social_status_isDeleted { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Citizen Citizen1 { get; set; }
        public virtual Social_Status_Type Social_Status_Type { get; set; }
    }
}
