//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.CertificateStudentM_M = new HashSet<CertificateStudentM_M>();
            this.UniversityStudentM_M = new HashSet<UniversityStudentM_M>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CitizenId { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<int> SpecializationFacultyId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<bool> IsGraduatedP { get; set; }
        public Nullable<bool> IsGraduatedS { get; set; }
        public Nullable<bool> IsGraduatedI { get; set; }
        public Nullable<bool> IsGraduatedU { get; set; }
        public string SchoolSection { get; set; }
        public Nullable<int> FacultyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificateStudentM_M> CertificateStudentM_M { get; set; }
        public virtual Citizen Citizen { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual School School { get; set; }
        public virtual SpecializationOfFaculty SpecializationOfFaculty { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UniversityStudentM_M> UniversityStudentM_M { get; set; }
    }
}
