//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccinationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VaccinationType()
        {
            this.ScheduleVaccM_M = new HashSet<ScheduleVaccM_M>();
            this.VaccinationReservations = new HashSet<VaccinationReservation>();
            this.VacinationHealthCareM_M = new HashSet<VacinationHealthCareM_M>();
        }
    
        public int vaccination_type_id { get; set; }
        public string vaccination_type_name { get; set; }
        public Nullable<int> vaccination_type_period { get; set; }
        public Nullable<bool> vaccination_isDeleted { get; set; }
        public string vaccination_type_name_arabic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleVaccM_M> ScheduleVaccM_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccinationReservation> VaccinationReservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacinationHealthCareM_M> VacinationHealthCareM_M { get; set; }
    }
}
