//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violation_CarLicenceM_M
    {
        public int Id { get; set; }
        public Nullable<int> CarLicenceId { get; set; }
        public Nullable<int> ViolationId { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Is_Paid { get; set; }
    
        public virtual CarLicence CarLicence { get; set; }
        public virtual Violation Violation { get; set; }
    }
}
