//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicely.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Violation()
        {
            this.Violation_CarLicenceM_M = new HashSet<Violation_CarLicenceM_M>();
        }
    
        public int Id { get; set; }
        public string ViolationName { get; set; }
        public Nullable<decimal> ViolationPrice { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string ViolationNameArabic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Violation_CarLicenceM_M> Violation_CarLicenceM_M { get; set; }
    }
}
